<?php

use Drupal\Core\Url;

function wmmeta_cron()
{
    \Drupal::getContainer()->get('wmmeta.scheduler')->runSchedule();
}

function wmmeta_theme()
{
    return [
        'meta_head_tags' => [
            'variables' => [
                'meta' => \Drupal::getContainer()->get('wmmeta.meta')->getDefaultMetaData(),
            ],
            'path' => drupal_get_path('module', 'wmmeta') . DIRECTORY_SEPARATOR . 'templates',
            'template' => 'head_tags',
        ]
    ];
}

function wmmeta_preprocess_html(&$variables)
{
    $variables['metaHeadTags'] = [
        '#theme' => 'meta_head_tags',
        '#meta' => \Drupal::getContainer()->get('wmmeta.meta')->getMetaData(),
    ];
}

function wmmeta_inline_entity_form_entity_form_alter(&$entityForm, FormStateInterface $form_state)
{
    $entityForm['seo_preview']['trigger'] = [
        '#markup' => sprintf(
            '<a href="%s" class="use-ajax button" data-dialog-type="dialog">%s</a>',
            Url::fromRoute('wmmeta.preview_modal')->toString(),
            t('Open preview')
        ),
        '#weight' => 10000,
    ];
}
